### ISSUE TITLE
support for images in Windows

### ISSUE THREAD

**Issue by prabirshrestha** [mfontanini/presenterm#115] opened 2024-01-04 06:08 UTC
It says that images are not supported on windows. Might be considering using termwiz? https://docs.rs/termwiz/latest/termwiz/escape/struct.Sixel.html

**Comment by mfontanini** [comment] 2024-01-06 17:23
See #13. This is a problem of getting the terminal window dimensions in pixels. I'll see if this can use some workaround, worse case letting you specify the dimensions by hand in a config file.

Closing this as it's a duplicate of #13.

**Closed by mfontanini** 2024-01-06 17:23 UTC

**Comment by mfontanini** [comment] 2024-01-09 03:26
See #13, this is starting to work.
