### ISSUE TITLE
Single-line comments don't work

### ISSUE THREAD

**Issue by jack-weilage** [mfontanini/presenterm#90] opened 2023-12-11 23:41 UTC
## Background

Prettier automatically converts presenterm's slide title format into a level-2 heading, so it's necessary to add a `<!-- prettier-ignore -->` comment.

```md
Slide Heading
---
```
becomes
```md
## Slide Heading
```

I saw the fix in #23, but, in my opinion, single-line comments should be expanded to allow anything inside. It's much more disruptive to have errors when you write a single-line comment than to accidentally write a comment command.

## Alternatives

You could just write
```md
<!--
prettier-ignore
-->
Slide Heading
---
```
but this seems like a pointless limitation.

**Comment by mfontanini** [comment] 2023-12-12 01:02
> than to accidentally write a comment command

The issue is not accidentally writing a comment command but trying to write one, making a mistake, and the command not doing anything because the error was ignored. The problem here is I don't want comment-command parsing to be best effort: if you write a comment command the app needs to ensure it's a valid one. e.g. if you write `paus` or `end_side` or `column_layout [3, 4]` this **must** fail. Otherwise you write your presentation thinking it will be displayed in one way and then you'll either not notice or you will be confused as to why the command isn't working because there's no messages anywhere indicating so.

I'd argue, rather than having to fight against prettier every time you write a slide heading, maybe it's worth disabling it globally? It seems like more of a hassle to have to tag every single slide title with a `prettier-ignore` (whether it's a single line or multi line) than just disabling it altogether. I'd also argue prettier is doing the wrong thing (and it seems like they have an [open issue about this](https://github.com/prettier/prettier/issues/6013)). 

I'm open to other solutions though. e.g. there could be a list of allowed single line comment commands in `~/.config/presenterm/config.yaml` or something. The only requirement is that if your intent is to write a comment command, then it must be a valid one.

**Comment by jack-weilage** [comment] 2023-12-12 01:54
> I'd also argue prettier is doing the wrong thing

100% agree!

> if you write a comment command the app needs to ensure it's a valid one.

Also agree, but completely replacing single-line comments with comment commands loses an important (at least to me) part of writing markdown. I often write a sentence or paragraph

IMO, there needs to be a distinction between comments and comment commands. Maybe a prefix?

```md
Something like
<!-- cmd:end_slide -->
```

This way, you can still write whatever comments you want (with the exception of ones starting with `cmd:`), and invalid commands fail (`cmd:end_side`).

Obviously this would be a huge breaking change, so there's probably a better way of doing this.

**Comment by mfontanini** [comment] 2023-12-12 03:46
Yeah maybe there should have been a prefix to disambiguate, but that makes commands even longer. Just like you'd be okay with something like that, other people (#65) want even shorter comment-commands so it's hard to keep everyone happy.

As you said, you can use multi-line comments to workaround this issue. 

Solutions we can implement here:
* Let you have a list of comments that you want to skip when parsing commands. This would work for the prettier case but not for any sentence you want in a single line so it's not great.
* Let you configure a prefix for commands. By default we still do `slide_end` but you can define a `command_prefix` in `~/.config/presenterm/config.yaml` where you can set an arbitrary string and only if the single-line comment-command starts with that, it is considered as such. Would this work?

**Comment by jack-weilage** [comment] 2023-12-12 21:53
The `command_prefix` option seems to be exactly what I'm looking for! The only problem I could see is if you are collaborating with someone who doesn't have the same prefix/no prefix. In that case, you would have to change your global settings to work on that project, then change them back to work on anything else.

Maybe a per-project setting could be added in the YAML frontmatter too?

**Comment by mfontanini** [comment] 2023-12-13 03:17
> The command_prefix option seems to be exactly what I'm looking for! 

Awesome! I'll work on that next.

> Maybe a per-project setting could be added in the YAML frontmatter too?

Yep, I was thinking of this as well. I'll do that too. There's barely anything in the config file yet so it hasn't turned up to be an issue but it will eventually.

**Comment by mfontanini** [comment] 2023-12-14 02:24
This should be fixed in master. I'm in the process of adding docs as part of the next release but for now:

[![asciicast](https://asciinema.org/a/3n0P4bpi4g4GEdas2C1cPrSOI.svg)](https://asciinema.org/a/3n0P4bpi4g4GEdas2C1cPrSOI)

**Closed** 2023-12-14 02:24 UTC
